name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'
        SOLUTION: 'CommerceApiSDK.sln'

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        fetch-depth: 0
    
    
    - name: Package nuget
      if: startsWith(github.ref, 'refs/heads/main')
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}

    - name: Push generated package to GitHub registry
      if: startsWith(github.ref, 'refs/heads/main')
      run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/commerce-csharp-sdk/index.json
